when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false
        # intercept_redirects: true # intercepte les redirections

    framework:
        profiler: { only_exceptions: false }

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { collect: false }
